export const THEMES = {
  vintage: {
    id: 'vintage',
    name: 'Vintage',
    // SVG map colors
    mapWater: '#c8d8e8',
    mapLand: '#d4c4a0',
    mapBorder: '#b0a080',
    // Pin & line
    pinColor: '#8b4513',
    pinBorder: '#f5e6c8',
    lineColor: '#a0522d',
    // Poster
    posterBg: '#f5e6c8',
    posterText: '#2c1810',
    posterSubtext: '#7a5230',
    posterAccent: '#b8813a',
    posterBorder: '#c9a96e',
    posterDivider: '#d4b896',
    titleFont: 'Playfair Display',
    bodyFont: 'Cormorant Garamond',
    separator: '✦',
  },
  dark: {
    id: 'dark',
    name: 'Dark',
    mapWater: '#0a0f1a',
    mapLand: '#1a2535',
    mapBorder: '#2a3a4a',
    pinColor: '#d4af37',
    pinBorder: '#0d1117',
    lineColor: '#d4af37',
    posterBg: '#0d1117',
    posterText: '#f0e6d3',
    posterSubtext: '#9a8060',
    posterAccent: '#d4af37',
    posterBorder: '#1e2a3a',
    posterDivider: '#1e2a3a',
    titleFont: 'Playfair Display',
    bodyFont: 'Cormorant Garamond',
    separator: '◆',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    mapWater: '#e8eef4',
    mapLand: '#d0d8e0',
    mapBorder: '#b0bcc8',
    pinColor: '#0a0a0a',
    pinBorder: '#ffffff',
    lineColor: '#333333',
    posterBg: '#ffffff',
    posterText: '#0a0a0a',
    posterSubtext: '#555555',
    posterAccent: '#0a0a0a',
    posterBorder: '#e0e0e0',
    posterDivider: '#e0e0e0',
    titleFont: 'Inter',
    bodyFont: 'Inter',
    separator: '—',
  },
};
